name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "/site"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/Site-Institucional/site"  # Definindo o diretório completo no servidor EC2

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Atualizar pacotes usando apt-get
            sudo apt-get update -y
            sudo apt-get install -y apache2

            # Iniciar e habilitar o Apache
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Navegar para o diretório correto e instalar Node.js e npm
            cd /home/ubuntu/Site-Institucional/site || exit
            if [ ! -f "package.json" ]; then
              echo "Erro: package.json não encontrado em /home/ubuntu/Site-Institucional/site"
              exit 1
            fi

            # Instalar dependências e fazer o build
            npm install
            npm run build

            # Verificar se o diretório de build foi criado
            if [ ! -d "build" ]; then
              echo "Erro: Diretório de build não encontrado após o comando npm run build"
              exit 1
            fi

            # Copiar arquivos de build para o diretório do Apache
            sudo cp -r build/* /var/www/html

            # Reiniciar o Apache para aplicar as alterações
            sudo systemctl restart apache2
